CREATE DATABASE VatLieu
USE VatLieu
CREATE TABLE Account(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
ChucVu INT NOT NULL,
TrangThai INT NOT NULL,
HoTen NVARCHAR(300) NOT NULL,
NgaySinh DATE NOT NULL,
GioiTinh BIT NOT NULL,
SDT NVARCHAR(12) NOT NULL,
DiaChi NVARCHAR(MAX) NOT NULL,
Email NVARCHAR(300) NOT NULL,
Username NVARCHAR(200) NOT NULL,
[Password] NVARCHAR(200) NOT NULL,
NgayTao DATE NOT NULL,
NguoiTao UNIQUEIDENTIFIER NOT NULL,
NgayChinhSua DATE,
NguoiChinhSua UNIQUEIDENTIFIER
)
CREATE TABLE KhachHang(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
HoTen NVARCHAR(300) NOT NULL,
NgaySinh DATE NOT NULL,
GioiTinh BIT NOT NULL,
SDT NVARCHAR(12) NOT NULL,
DiaChi NVARCHAR(MAX) NOT NULL,
Email NVARCHAR(300) NOT NULL,
NgayTao DATE NOT NULL,
NguoiTao UNIQUEIDENTIFIER NOT NULL,
NgayChinhSua DATE,
NguoiChinhSua UNIQUEIDENTIFIER
)
CREATE TABLE SanPham(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma NVARCHAR(20) NOT NULL,
TenSP NVARCHAR(300) NOT NULL,
)
CREATE TABLE Loai(
Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
Ma NVARCHAR(20) NOT NULL,
Ten NVARCHAR(300) NOT NULL,
)
CREATE TABLE Hang(
Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
Ma NVARCHAR(20) NOT NULL,
Ten NVARCHAR(300) NOT NULL,
)
CREATE TABLE ChiTietSanPham(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
IdSP UNIQUEIDENTIFIER NOT NULL,
IdHang INT NOT NULL,
IdLoai INT NOT NULL,
DonViTinh NVARCHAR(100) NOT NULL,
SoLuongTon FLOAT NOT NULL,
GiaNhap MONEY NOT NULL,
GiaBan MONEY NOT NULL,
NgayNhap DATE NOT NULL,
NgayChinhSua DATE,
CONSTRAINT FK_IdSP FOREIGN KEY (IdSP) REFERENCES SanPham(Id),
CONSTRAINT FK_IdHang FOREIGN KEY (IdHang) REFERENCES Hang(Id),
CONSTRAINT FK_IdLoaiSP FOREIGN KEY (IdLoai) REFERENCES Loai(Id),
)
CREATE TABLE HoaDon(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
IdAcc UNIQUEIDENTIFIER NOT NULL,
IdKH UNIQUEIDENTIFIER,
IdTT INT NOT NULL,
Ten NVARCHAR(100) NOT NULL,
NgayTao DATE NOT NULL,
NgayThanhToan DATE,
NgayShip DATE,
NgayKhachNhan DATE,
TongTien MONEY NOT NULL,
NgayChinhSua DATE,
NguoiChinhSua UNIQUEIDENTIFIER
CONSTRAINT FK_IdAcc FOREIGN KEY (IdAcc) REFERENCES Account(Id),
CONSTRAINT FK_IdKH FOREIGN KEY (IdKH) REFERENCES KhachHang(Id)
)
CREATE TABLE HoaDonChiTiet(
IdCTSP UNIQUEIDENTIFIER NOT NULL,
IdHoaDon UNIQUEIDENTIFIER NOT NULL,
TenSP NVARCHAR(300) NOT NULL,
Hang NVARCHAR(300) NOT NULL,
Loai NVARCHAR(300) NOT NULL,
DonViTinh NVARCHAR(200) NOT NULL,
SoLuong FLOAT NOT NULL,
DonGia MONEY NOT NULL
CONSTRAINT PK_IdCTSP_IdHD PRIMARY KEY (IdCTSP,IdHoaDon),
CONSTRAINT FK_IdCTSP FOREIGN KEY (IdCTSP) REFERENCES ChiTietSanPham(Id),
CONSTRAINT FK_IdHD FOREIGN KEY (IdHoaDon) REFERENCES HoaDon(Id)
)
CREATE TABLE GioHang(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
IdKH UNIQUEIDENTIFIER,
NgayTao DATE NOT NULL,
TongTien MONEY NOT NULL
CONSTRAINT FK_IdGHKH FOREIGN KEY (IdKH) REFERENCES KhachHang(Id),
)
CREATE TABLE GioHangChiTiet(
IdCTSP UNIQUEIDENTIFIER NOT NULL,
IdHoaDon UNIQUEIDENTIFIER NOT NULL,
TenSP NVARCHAR(300) NOT NULL,
Hang NVARCHAR(300) NOT NULL,
Loai NVARCHAR(300) NOT NULL,
DonViTinh NVARCHAR(200) NOT NULL,
SoLuong FLOAT  NOT NULL,
DonGia MONEY NOT NULL
CONSTRAINT PK_IdCTSP_IdGH PRIMARY KEY (IdCTSP,IdHoaDon),
CONSTRAINT FK_IdGHCTSP FOREIGN KEY (IdCTSP) REFERENCES ChiTietSanPham(Id),
CONSTRAINT FK_IdGH FOREIGN KEY (IdHoaDon) REFERENCES HoaDon(Id)
)
INSERT INTO Account(ChucVu,TrangThai,HoTen,GioiTinh,Email,SDT,DiaChi,NgayTao,NguoiTao,Username,[Password],NgaySinh)
VALUES(1,1,'Huy',0,'huytqph26085','0295932235','sfasghasgas',GETDATE(),'871C6EAC-FEE8-49C1-A079-20E274AF113E','HUYTQPH26085','123456','03/03/2003')
SELECT [ID],  [Username]
              ,[Password]
                     
 FROM [dbo].[Account] WHERE [Username] = 'HUYTQPH26085'  and [Password] = '123456'
