CREATE DATABASE VatLieu
USE VatLieu
CREATE TABLE Account(
Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
TrangThai INT NOT NULL,
HoTen NVARCHAR(300) NOT NULL,
GioiTinh BIT NOT NULL,
Username NVARCHAR(200) NOT NULL,
[Password] NVARCHAR(200) NOT NULL,
NgayTao DATE NOT NULL,
NguoiTao INT NOT NULL,
NgayChinhSua DATE,
NguoiChinhSua INT
)
CREATE TABLE KhachHang(
Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
HoTen NVARCHAR(300) NOT NULL,
NgaySinh DATE NOT NULL,
GioiTinh BIT NOT NULL,
SDT NVARCHAR(12) NOT NULL,
DiaChi NVARCHAR(MAX) NOT NULL,
Email NVARCHAR(300) NOT NULL,
NgayTao DATE NOT NULL,
NguoiTao INT NOT NULL,
NgayChinhSua DATE,
NguoiChinhSua INT
)
CREATE TABLE SanPham(
Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
Ma NVARCHAR(20) NOT NULL,
TenSP NVARCHAR(300) NOT NULL,
)
CREATE TABLE Loai(
Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
Ma NVARCHAR(20) NOT NULL,
Ten NVARCHAR(300) NOT NULL,
)
CREATE TABLE Hang(
Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
Ma NVARCHAR(20) NOT NULL,
Ten NVARCHAR(300) NOT NULL,
)
CREATE TABLE ChiTietSanPham(
Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
IdSP INT NOT NULL,
IdHang INT NOT NULL,
IdLoai INT NOT NULL,
DonViTinh NVARCHAR(100) NOT NULL,
SoLuongTon FLOAT NOT NULL,
GiaNhap MONEY NOT NULL,
GiaBan MONEY NOT NULL,
NgayNhap DATE NOT NULL,
NguoiNhap INT NOT NULL,
NguoiChinhSua INT,
NgayChinhSua DATE,
CONSTRAINT FK_IdSP FOREIGN KEY (IdSP) REFERENCES SanPham(Id),
CONSTRAINT FK_IdHang FOREIGN KEY (IdHang) REFERENCES Hang(Id),
CONSTRAINT FK_IdLoaiSP FOREIGN KEY (IdLoai) REFERENCES Loai(Id),
)
CREATE TABLE HoaDon(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
IdAcc INT,
IdKH INT,
IdTT INT NOT NULL,
Ten NVARCHAR(100) NOT NULL,
NgayTao DATE NOT NULL,
NgayThanhToan DATE,
NgayShip DATE,
NgayKhachNhan DATE,
TongTien MONEY NOT NULL,
NgayChinhSua DATE,
NguoiChinhSua INT
CONSTRAINT FK_IdAcc FOREIGN KEY (IdAcc) REFERENCES Account(Id),
CONSTRAINT FK_IdKH FOREIGN KEY (IdKH) REFERENCES KhachHang(Id)
)
CREATE TABLE HoaDonChiTiet(
IdCTSP INT NOT NULL,
IdHoaDon UNIQUEIDENTIFIER NOT NULL,
TenSP NVARCHAR(300) NOT NULL,
Hang NVARCHAR(300) NOT NULL,
Loai NVARCHAR(300) NOT NULL,
DonViTinh NVARCHAR(200) NOT NULL,
SoLuong FLOAT NOT NULL,
DonGia MONEY NOT NULL
CONSTRAINT PK_IdCTSP_IdHD PRIMARY KEY (IdCTSP,IdHoaDon),
CONSTRAINT FK_IdCTSP FOREIGN KEY (IdCTSP) REFERENCES ChiTietSanPham(Id),
CONSTRAINT FK_IdHD FOREIGN KEY (IdHoaDon) REFERENCES HoaDon(Id)
)
INSERT INTO SanPham(Ma,TenSP) VALUES
('SP1','Sat'),
('SP2','Xi'),
('SP3','Gach'),
('SP4','Mat')
INSERT INTO Loai(Ma,Ten) VALUES
('L1','Loai1'),
('L2','Loai2'),
('L3','Loai3'),
('L4','Loai4')
INSERT INTO Hang(Ma,Ten) VALUES
('H1','HangA'),
('H2','HangB'),
('H3','HangC'),
('H4','HangD')
INSERT INTO ChiTietSanPham(IdSP,IdHang,IdLoai,DonViTinh,SoLuongTon,GiaNhap,GiaBan,NgayNhap,NguoiNhap)
VALUES
(1,3,2,'Bao',200,60000,80000,'10/10/2019',0),
(2,1,1,'KG',300,15000,19000,'09/06/2018',0),
(3,2,4,'Vien',20000,1000,2500,'03/05/2020',0)
SELECT * FROM SanPham
SELECT * FROM Hang
SELECT * FROM Loai
SELECT * FROM ChiTietSanPham
INSERT INTO KhachHang(HoTen,NgaySinh,GioiTinh,SDT,DiaChi,Email,NgayTao,NguoiTao)
VALUES ('Ba H','04/01/1967',1,'07124992758','AFASFSAGU','AB.@gmail.com','12/12/2021',0)
SELECT * FROM Account
DELETE Account WHERE Id = 8
SELECT * FROM KhachHang
INSERT INTO HoaDon(IdAcc,IdKH,IdTT,Ten,NgayTao,TongTien) VALUES
(1,4,0,'Hoa Don A','10/10/2022',9000000),
(2,2,1,'Hoa Don B','09/09/2022',3000000),
(1,1,1,'Hoa Don C','08/08/2022',4000000)
